<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
$config['next_link'] = 'Siguiente';
$config['next_tag_open'] = '<span class="nav-enabled">';
$config['next_tag_close'] = '</span>';
$config['prev_link'] = 'Anterior';
$config['prev_tag_open'] = '<span class="nav-enabled">';
$config['prev_tag_close'] = '</span>';
$config['first_link'] = 'Primero';
$config['first_tag_open'] = '<span class="nav-enabled">';
$config['first_tag_close'] = '</span>';
$config['last_link'] = 'Último';
$config['last_tag_open'] = '<span class="nav-enabled">';
$config['last_tag_close'] = '</span>';
$config['cur_tag_open'] = '<span class="active">';
$config['cur_tag_close'] = '</span>';
$config['num_tag_open'] = '<span>';
$config['num_tag_close'] = '</span>';
$config['per_page'] = 20;
